version: '3.1'

service:

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: passwd
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
